### ISSUE TITLE
Filter about more columns

### ISSUE THREAD

**Issue by jeyraof** [OllegK/InstagramHelper#20]
Can I filter on table of result such as `follows_viewer is False`?
Not on downloaded excel, but on chrome tab.

**Comment by OllegK** [comment]
You need to wait when detailed info is collected. The entire process consists of two steps:
1) Creating a "short" list of followers/following accounts. When it is completed, a table is displayed, but it has just a few columns.  However, it gives ability to filter by "follows_user". So if you created a list of your followers/following, you could find the accounts you follow and who not follow you back at this point. Otherwise, you need to wait when the second step is completed.
2) Getting the more information on each account. It requires a separate HTTP request for each account, so the process takes a long time, especially if the list contains several thousand accounts. When it is completed, the table with more columns is displayed. In the meantime, you can export to Excel when this second step is still running, but the results will not be accurate, because not all accounts are processed yet anyway.

**Comment by jeyraof** [comment]
@OllegK Thanks you ^^
