### ISSUE TITLE
Not receiving full list of users.

### ISSUE THREAD

**Issue by awelch83** [OllegK/InstagramHelper#26]
Why is the following occuring? The numbers do not look right (see bold-highlighted text):

Completed, detailed info collection was cancelled, spent time - 0h:15m:46s, **created list length - 2808** (follows - 4277(actually returned 0), **followed by - 2818(actually returned 2808))**, sent HTTP requests - 289

Why didn't the helper produce a list of 2818 users?

**Comment by OllegK** [comment]
Hello! I am a perfectionist and like the accuracy, therefore I coded that to indicate the difference when it happens: when extension asked for user profile instagram returned 2818 followers, and when extension fetched all users instagram returned only 2808 users. I think it is just because the number on the profile sometimes is not updated immediately when follow/unfollow happens. It happens quite often, but usually the difference is 1-2.

**Comment by awelch83** [comment]
Thanks for your quick reply, Олег 😊 This makes sense to me now

Since this is open source, may I assume that you welcome assistance with the development of different features?

Sent from my iPhone

On Dec 12, 2018, at 14:11, Oleg <notifications@github.com> wrote:

Hello! I am a perfectionist and like the accuracy, therefore I coded that to indicate the difference when it happens: when extension asked for user profile instagram returned 2818 followers, and when extension fetched all users instagram returned only 2808 users. I think it is just because the number on the profile sometimes is not updated immediately when follow/unfollow happens. It happens quite often, but usually the difference is 1-2.

**Comment by OllegK** [comment]
Yes, you are welcome, I don't have the contribution guide yet, but maybe we could meet to discuss that on online meeting.
