### ISSUE TITLE
Crashing on export to Excel

### ISSUE THREAD

**Issue by marconnor** [OllegK/InstagramHelper#30]
Hi, I have tried to generate a list of accounts that are following a user (followers) and it completes getting the detailed info however, when you ask it to generate it to XLSX it snaps and you receive a SNAP something went wrong and offers to reload. The problem with the reload is the data is lost.

I have tried using the Developer Tools to obtain an error log but nothing is available when it snaps. The number of followers is 16,600. This also happened on an account that had 30,500 followers and after many attempts (over 5), I finally obtained a list.

I am using Chrome on a VPS with nothing else running on it.  I have tried changing options for Page size for fetching users (insta and common users): from 10, then 30 (where I had success with the 30k follower list) to 40.

These problems have only started happening in the last month. I have successfully generated large lists through out the year. Has something changed?

**Comment by OllegK** [comment]
Hi! My understanding that whenever it crashes on the trying to export is a lack of memory that Chrome can allocate for the extension. Therefore the issue could be caused by Chrome version, configuration, OS and platform. The only change happened in XLSX export over the last several months - on 22nd December was released a new version that added several new columns into the outputs that could ask a little bit more memory. 

Yesterday I tried to export 64k, for 24k of them the detailed info was already collected, into XLSX/CSV and observed the following: 
1. During CSV export the memory consumption was increased by 700M.
2. During XLSX export the memory consumption was increased by almost 3.5G, and the total JavaScript Memory consumed by extension was very close to 4G.

I did not find how much memory could be allocated by Chrome/Chromium to one process, but it could be that 4G is a limit, therefore for XLSX export I almost touched the ceiling. Considering that 4G is a limit value, CSV export could hit the limit exporting about 100-120k accounts with collected detailed info. 

There are several options for how to improve the export capabilities, and for now, the only option is CSV export. Please try it, it works faster and consumes less memory, so it will allow exporting more, but anyway has the limit.

The page size doesn't affect the export functionality, however, if higher value works for you, you can keep it, and the initial list comes faster.

**Comment by marconnor** [comment]
Thank you for your quick reply. I was able to successfully export an XLSX and CVS list on my local laptop. I experienced a crash again on the VPS and this time it told me it was out of memory. I find it strange that memory would be an issue when it is the only task running. My technology experience is limited so I'm not sure how to analyse all this. If there is information I can obtain and provide, please let me know.

**Comment by OllegK** [comment]
It could be that amount of memory on the expensive laptop could be higher than on the dedicated server. Also it makes difference how much memory could be allocated to the one process, and it depends on many criteria, including OS, platform, and Chrome version. One guy told me that he was able to export about 80k accounts with the detailed info collected; it is the highest exported amount I am aware of.
